/**
 * Flattens every docs page into one plain-text bundle the support AI reads
 * in full on each question.
 *
 * The whole knowledgebase is ~12k tokens, so it goes into the prompt as is:
 * no embeddings, no vector index, no chunking to get wrong. Revisit when the
 * bundle passes ~100k tokens (the script prints its size on every build).
 *
 * It runs as an Astro integration rather than a package.json step so the
 * bundle is regenerated by any build, however Cloudflare Pages invokes it.
 * Pages compiles `functions/` after the build command, so the generated
 * module is in place by the time `server/` imports it.
 */
import { readdir, readFile, writeFile } from 'node:fs/promises'
import { join, relative, sep } from 'node:path'
import { fileURLToPath } from 'node:url'

const DOCS_DIR = fileURLToPath(new URL('../src/content/docs/', import.meta.url))
const OUT_FILE = fileURLToPath(new URL('../server/kb.generated.js', import.meta.url))

/**
 * Things that must never reach the public docs, and so never the support AI,
 * which reads every page verbatim. Internal notes (the app repo's SUPPORT.md)
 * are full of them, so content copied from there is checked on every build.
 * A match fails the build, naming the file and the rule.
 */
const SENSITIVE = [
  ['an OpenRouter API key', /sk-or-v1-[A-Za-z0-9]{16,}/],
  ['a payment-provider or cloud secret', /\b(?:sk|rk)_(?:live|test)_[A-Za-z0-9]{8,}|\bAKIA[0-9A-Z]{16}\b|\bgh[pousr]_[A-Za-z0-9]{20,}|\bxox[abpr]-[A-Za-z0-9-]{10,}/],
  ['a private key', /-----BEGIN [A-Z ]*PRIVATE KEY-----/],
  // Customer-facing settings the docs teach people to fill in themselves are allowed (see below).
  ['a secret variable name', /\b(?!GITHUB_PERSONAL_ACCESS_TOKEN\b)[A-Z][A-Z0-9_]*_(?:SECRET|TOKEN|PASSWORD|API_KEY)\b|X-Internal-Secret/],
  ['an IP address', /\b(?:\d{1,3}\.){3}\d{1,3}\b/],
  ['an internal server or database', /audio\.hey(?:odin|silk)ai\.com|\bodin-waitlist\b|\bwrangler\s+d1\b|\b(?:purchase_events|license_devices|activation_tokens)\b/],
  ['an internal link or code', /calendly\.com|kvsocial|ijuwebdesk\/learn|OdinExclusive|dfy\?k=/i],
  ['a payment-platform product ID', /\b(?:product|bump|upsell)-\d{2,}\b/],
]
const PUBLIC_EMAILS = new Set(['support@heysilkai.com', 'hello@heysilkai.com'])

function assertPublishable(file, source) {
  const where = relative(DOCS_DIR, file)
  for (const [what, pattern] of SENSITIVE) {
    const match = source.match(pattern)
    if (match) throw new Error(`${where} contains ${what} ("${match[0]}"). Remove it: the docs are public and feed the support AI.`)
  }
  for (const email of source.match(/[\w.+-]+@[\w-]+(?:\.[\w-]+)+/g) ?? []) {
    if (!PUBLIC_EMAILS.has(email.toLowerCase())) {
      throw new Error(`${where} contains the email address ${email}. Only ${[...PUBLIC_EMAILS].join(' and ')} may appear in the docs.`)
    }
  }
}

async function listDocs(dir) {
  const entries = await readdir(dir, { withFileTypes: true })
  const files = await Promise.all(
    entries.map((e) => {
      const path = join(dir, e.name)
      if (e.isDirectory()) return listDocs(path)
      return /\.mdx?$/.test(e.name) ? [path] : []
    }),
  )
  return files.flat().sort()
}

/** `features/memory.mdx` -> `/features/memory/`, `index.mdx` -> `/`. */
function urlFor(file) {
  const slug = relative(DOCS_DIR, file).split(sep).join('/').replace(/\.mdx?$/, '')
  if (slug === 'index') return '/'
  return `/${slug.replace(/\/index$/, '')}/`
}

function frontmatterField(frontmatter, key) {
  const match = frontmatter.match(new RegExp(`^${key}:\\s*(.+)$`, 'm'))
  return match ? match[1].trim().replace(/^['"]|['"]$/g, '') : ''
}

function attr(attrs, name) {
  const match = attrs.match(new RegExp(`${name}=(?:"([^"]*)"|'([^']*)'|\\{['"]([^'"]*)['"]\\})`))
  return match ? (match[1] ?? match[2] ?? match[3]) : ''
}

/** MDX to the plain markdown a model reads best: components become prose. */
function toPlainMarkdown(body) {
  // Code is set aside first so placeholders like `Silk-<version>.dmg` survive
  // the tag stripping below.
  const code = []
  const stash = (match) => `\u0000${code.push(match) - 1}\u0000`
  return (
    body
      .replace(/```[\s\S]*?```|`[^`\n]+`/g, stash)
      .replace(/^import .*$/gm, '')
      // <Aside type="caution" title="Heads up"> -> a labelled blockquote opener
      .replace(/<Aside([^>]*)>/g, (_, attrs) => {
        const type = attr(attrs, 'type') || 'note'
        const title = attr(attrs, 'title')
        return `\n**${type[0].toUpperCase()}${type.slice(1)}${title ? `: ${title}` : ''}:**`
      })
      .replace(/<LinkCard([\s\S]*?)\/>/g, (_, attrs) => {
        const description = attr(attrs, 'description')
        return `- [${attr(attrs, 'title')}](${attr(attrs, 'href')})${description ? ` — ${description}` : ''}`
      })
      .replace(/<Card([^>]*)>/g, (_, attrs) => `\n**${attr(attrs, 'title')}**\n`)
      .replace(/<TabItem([^>]*)>/g, (_, attrs) => `\n**${attr(attrs, 'label')}:**\n`)
      .replace(/<iframe([\s\S]*?)\/?>/g, (_, attrs) => `[Video: ${attr(attrs, 'title') || 'embedded video'}]`)
      .replace(/<a\s[^>]*href="([^"]*)"[^>]*>([\s\S]*?)<\/a>/g, '[$2]($1)')
      // Any other tag (Steps, CardGrid, layout divs) is structure, not content.
      .replace(/<\/?[A-Za-z][^>]*>/g, '')
      .replace(/[ \t]+$/gm, '')
      .replace(/\n{3,}/g, '\n\n')
      .replace(/\u0000(\d+)\u0000/g, (_, i) => code[i])
      .trim()
  )
}

export async function buildKnowledgeBundle() {
  const files = await listDocs(DOCS_DIR)
  const pages = await Promise.all(
    files.map(async (file) => {
      const source = await readFile(file, 'utf8')
      assertPublishable(file, source)
      const [, frontmatter = '', body = source] = source.match(/^---\n([\s\S]*?)\n---\n([\s\S]*)$/) ?? []
      return {
        url: urlFor(file),
        title: frontmatterField(frontmatter, 'title'),
        description: frontmatterField(frontmatter, 'description'),
        text: toPlainMarkdown(body),
      }
    }),
  )

  const docs = pages
    .map((p) => `=== PAGE: ${p.title}\nURL: ${p.url}\n${p.description ? `Summary: ${p.description}\n` : ''}\n${p.text}`)
    .join('\n\n')
  const index = pages.map((p) => ({ url: p.url, title: p.title }))

  await writeFile(
    OUT_FILE,
    `// Generated by integrations/support-kb.mjs on every build. Do not edit.\n` +
      `export const DOCS = ${JSON.stringify(docs)}\n` +
      `export const PAGES = ${JSON.stringify(index)}\n`,
  )
  return { pages: pages.length, chars: docs.length }
}

export default function supportKnowledgeBundle() {
  return {
    name: 'support-kb',
    hooks: {
      'astro:config:setup': async ({ logger }) => {
        const { pages, chars } = await buildKnowledgeBundle()
        logger.info(`${pages} pages, ~${Math.round(chars / 4 / 1000)}k tokens -> server/kb.generated.js`)
      },
    },
  }
}
