/**
 * Flattens every docs page into one plain-text bundle the support AI reads
 * in full on each question.
 *
 * The whole knowledgebase is ~12k tokens, so it goes into the prompt as is:
 * no embeddings, no vector index, no chunking to get wrong. Revisit when the
 * bundle passes ~100k tokens (the script prints its size on every build).
 *
 * It runs as an Astro integration rather than a package.json step so the
 * bundle is regenerated by any build, however Cloudflare Pages invokes it.
 * Pages compiles `functions/` after the build command, so the generated
 * module is in place by the time `server/` imports it.
 */
import { readdir, readFile, writeFile } from 'node:fs/promises'
import { join, relative, sep } from 'node:path'
import { fileURLToPath } from 'node:url'

const DOCS_DIR = fileURLToPath(new URL('../src/content/docs/', import.meta.url))
const OUT_FILE = fileURLToPath(new URL('../server/kb.generated.js', import.meta.url))

async function listDocs(dir) {
  const entries = await readdir(dir, { withFileTypes: true })
  const files = await Promise.all(
    entries.map((e) => {
      const path = join(dir, e.name)
      if (e.isDirectory()) return listDocs(path)
      return /\.mdx?$/.test(e.name) ? [path] : []
    }),
  )
  return files.flat().sort()
}

/** `features/memory.mdx` -> `/features/memory/`, `index.mdx` -> `/`. */
function urlFor(file) {
  const slug = relative(DOCS_DIR, file).split(sep).join('/').replace(/\.mdx?$/, '')
  if (slug === 'index') return '/'
  return `/${slug.replace(/\/index$/, '')}/`
}

function frontmatterField(frontmatter, key) {
  const match = frontmatter.match(new RegExp(`^${key}:\\s*(.+)$`, 'm'))
  return match ? match[1].trim().replace(/^['"]|['"]$/g, '') : ''
}

function attr(attrs, name) {
  const match = attrs.match(new RegExp(`${name}=(?:"([^"]*)"|'([^']*)'|\\{['"]([^'"]*)['"]\\})`))
  return match ? (match[1] ?? match[2] ?? match[3]) : ''
}

/** MDX to the plain markdown a model reads best: components become prose. */
function toPlainMarkdown(body) {
  // Code is set aside first so placeholders like `Silk-<version>.dmg` survive
  // the tag stripping below.
  const code = []
  const stash = (match) => `\u0000${code.push(match) - 1}\u0000`
  return (
    body
      .replace(/```[\s\S]*?```|`[^`\n]+`/g, stash)
      .replace(/^import .*$/gm, '')
      // <Aside type="caution" title="Heads up"> -> a labelled blockquote opener
      .replace(/<Aside([^>]*)>/g, (_, attrs) => {
        const type = attr(attrs, 'type') || 'note'
        const title = attr(attrs, 'title')
        return `\n**${type[0].toUpperCase()}${type.slice(1)}${title ? `: ${title}` : ''}:**`
      })
      .replace(/<LinkCard([\s\S]*?)\/>/g, (_, attrs) => {
        const description = attr(attrs, 'description')
        return `- [${attr(attrs, 'title')}](${attr(attrs, 'href')})${description ? ` — ${description}` : ''}`
      })
      .replace(/<Card([^>]*)>/g, (_, attrs) => `\n**${attr(attrs, 'title')}**\n`)
      .replace(/<TabItem([^>]*)>/g, (_, attrs) => `\n**${attr(attrs, 'label')}:**\n`)
      .replace(/<iframe([\s\S]*?)\/?>/g, (_, attrs) => `[Video: ${attr(attrs, 'title') || 'embedded video'}]`)
      .replace(/<a\s[^>]*href="([^"]*)"[^>]*>([\s\S]*?)<\/a>/g, '[$2]($1)')
      // Any other tag (Steps, CardGrid, layout divs) is structure, not content.
      .replace(/<\/?[A-Za-z][^>]*>/g, '')
      .replace(/[ \t]+$/gm, '')
      .replace(/\n{3,}/g, '\n\n')
      .replace(/\u0000(\d+)\u0000/g, (_, i) => code[i])
      .trim()
  )
}

export async function buildKnowledgeBundle() {
  const files = await listDocs(DOCS_DIR)
  const pages = await Promise.all(
    files.map(async (file) => {
      const source = await readFile(file, 'utf8')
      const [, frontmatter = '', body = source] = source.match(/^---\n([\s\S]*?)\n---\n([\s\S]*)$/) ?? []
      return {
        url: urlFor(file),
        title: frontmatterField(frontmatter, 'title'),
        description: frontmatterField(frontmatter, 'description'),
        text: toPlainMarkdown(body),
      }
    }),
  )

  const docs = pages
    .map((p) => `=== PAGE: ${p.title}\nURL: ${p.url}\n${p.description ? `Summary: ${p.description}\n` : ''}\n${p.text}`)
    .join('\n\n')
  const index = pages.map((p) => ({ url: p.url, title: p.title }))

  await writeFile(
    OUT_FILE,
    `// Generated by integrations/support-kb.mjs on every build. Do not edit.\n` +
      `export const DOCS = ${JSON.stringify(docs)}\n` +
      `export const PAGES = ${JSON.stringify(index)}\n`,
  )
  return { pages: pages.length, chars: docs.length }
}

export default function supportKnowledgeBundle() {
  return {
    name: 'support-kb',
    hooks: {
      'astro:config:setup': async ({ logger }) => {
        const { pages, chars } = await buildKnowledgeBundle()
        logger.info(`${pages} pages, ~${Math.round(chars / 4 / 1000)}k tokens -> server/kb.generated.js`)
      },
    },
  }
}
